@startuml DataType

abstract AbstractData

abstract AbstractData <T> {
    + {static} HashMap<String, AbstractData> loaded
    + {static} AbstractData create()
    + AbstractData lock()
    + void close()
    + String getKey()
}

abstract SmallData <T> extends SimpleData {

}

abstract LargeData <T> extends SimpleData {

}

abstract SimpleData<T> extends AbstractData {
    + {static} HashMap<String, SimpleData> loaded
    + T get()
    + boolean set()
    + boolean setIfEmpty()
}

class Invalid extends AbstractData {

}

abstract NumericData<T> extends SmallData {
    + {abstract} T add();
    + {abstract} T sub();
    + {abstract} T mul();
    + {abstract} T div();
}

class RBoolean extends SmallData {
    
}

class RChar extends NumericData {
    
}

class RString extends SmallData {
    
}

class RVector extends SmallData {
    
}

class RWrapper extends SmallData {
    + void setIfEmpty()
    + T getDefaultValue()
}

class RByte extends NumericData {
    
}

class RShort extends NumericData {
    
}

class RInteger extends NumericData {

}

class RLong extends NumericData {
    
}

class RFloat extends NumericData {
    
}

class RDouble extends NumericData {

}


class RItemStack extends LargeData {
    
}

class RByteArray extends LargeData {
    
}

class RJson extends LargeData {
    + boolean hasKey()
    + String getAsString()
    + String getAsInt()
    + String getAsLong()
    + String getAsDouble()
    + String getAsBoolean()
    + String getAsEnum()
    + String getAsNumber()
    + void putString()
    + void putInt()
    + void putLong()
    + void putDouble()
    + void putBoolean()
    + void putEnum()
}


abstract CompositeData <T extends AbstractData,E> extends AbstractData {
    + {static} HashMap<String, CompositeData<?,?>> loaded
    + void set()
    + boolean removeKey()
    + void clear()
    + boolean contains()
    + boolean containsKey()
    + boolean containsValue()
    + boolean containsAll()
    + boolean isEmpty()
    + Iterator<T> iterator()
    + int size()
    + Object[] toArray()
    + F[] toArray()
}

class RList <T extends AbstractData> extends CompositeData {
    + boolean add()
    + void add()
    + boolean addAll()
    + T get()
    + int indexOf()
    + int lastIndexOf()
    + ListIterator<T> listIterator()
    + boolean remove()
    + List<Integer> indicesOf()
    + T remove()
    + boolean removeAll()
    + boolean retainAll()
    + T set()
    + List<T> subList()

}

CompositeData o-- AbstractData

abstract AbstractObject extends AbstractData {

}

AbstractObject *-- AbstractData



@enduml