@startuml DataType

interface SimpleInterface<T> {
    + T get()
    + boolean set()
    + boolean setIfEmpty()
}

interface ByteDataInterface {
    + byte[] getData();
    + Bytes getBytes();
}

class Bytes implements ByteDataInterface {
    + Bytes append()
    + void set()
}

enum JedisCommunicationChannel implements ByteDataInterface {
    + int getId()
}


abstract AbstractData <T> {
    + {static} HashMap<Bytes, AbstractData> loaded
    + {static} AbstractData create()
    + AbstractData lock()
    + boolean tryLockMultiple()
    + void close()
    + void unlockMultiple()
    + Bytes getKey()
    + String asString()
    + double getSortScore()
}

abstract SmallData <T> extends SimpleData {

}

abstract LargeData <T> extends SimpleData {

}

abstract SimpleData<T> extends AbstractData implements SimpleInterface {
    + {static} HashMap<Bytes, SimpleData> loaded
}

class Invalid extends AbstractData {

}

abstract NumericData<T> extends SmallData {
    + {abstract} T add();
    + {abstract} T sub();
    + {abstract} T mul();
    + {abstract} T div();
}

class RBoolean extends SmallData {
    
}

class RCharacter extends SmallData {
    
}

class RString extends SmallData {
    
}

class RVector extends SmallData {
    
}

class RWrapper<T> extends SmallData {
    + void setIfEmpty()
    + T getDefaultValue()
}

class RByte extends NumericData {
    
}

class RShort extends NumericData {
    
}

class RInteger extends NumericData {

}

class RLong extends NumericData {
    
}

class RFloat extends NumericData {
    
}

class RDouble extends NumericData {

}


class RItemStack extends LargeData {
    
}

class RByteArray extends LargeData {
    
}

class RJson extends LargeData {
    + boolean hasKey()
    + String getAsString()
    + int getAsInt()
    + long getAsLong()
    + double getAsDouble()
    + boolean getAsBoolean()
    + Enum getAsEnum()
    + Number getAsNumber()
    + void putString()
    + void putInt()
    + void putLong()
    + void putDouble()
    + void putBoolean()
    + void putEnum()
}

abstract OwnerData<T> extends AbstractData {
    + void deleteChild();
}

abstract CompositeData <T extends AbstractData> extends OwnerData {
    + {static} HashMap<Bytes, CompositeData<?,?>> loaded
    + void clear()
    + boolean isEmpty()
    + int size()
}

abstract CollectionData <T extends AbstractData,\nE extends Collection<T>> extends CompositeData implements Collection {
    + void set()
    + boolean removeKey()
    + boolean contains()
    + boolean containsAll()
    + boolean containsKey()
    + boolean containsValue()
    + getByKey()
    + getByValue()
    + removeByKey()
    + removeByValue()
    + Iterator<T> iterator()
    + Object[] toArray()
    + F[] toArray()
}

class RList <T extends AbstractData> extends CollectionData {
    + {static} HashMap<Bytes, RList> loaded
    + boolean add()
    + void add()
    + boolean addAll()
    + T get()
    + int indexOf()
    + int lastIndexOf()
    + ListIterator<T> listIterator()
    + boolean remove()
    + List<Integer> indicesOf()
    + T remove()
    + boolean removeAll()
    + boolean retainAll()
    + T set()
    + List<T> subList()

}

class RSet <T extends AbstractData> extends CollectionData {
    + {static} HashMap<Bytes, RList> loaded
    + boolean add()
    + boolean addAll()
    + boolean remove()
    + boolean removeAll()
    + boolean retainAll()
}

class RMap <Bytes, T extends AbstractData> extends CompositeData {
    + {static} HashMap<Bytes, RMap> loaded
    + boolean containsKey()
    + boolean containsValue()
    + Set<Entry<Bytes, T>> entrySet()
    + T get(Object arg0)
    + Set<Bytes> keySet()
    + T put()
    + void putAll()
    + T remove()
    + Collection<T> values()
}

RMap *-- SlaveCollection


class SlaveCollection <T extends AbstractData> implements Collection {
    + void clear()
    + boolean contains()
    + boolean containsAll()
    + boolean isEmpty()
    + Iterator<T> iterator()
    + boolean remove()
    + boolean removeAll()
    + boolean retainAll()
    + int size()
    + Object[] toArray()
    + F[] toArray()
}

CompositeData o-- AbstractData

abstract AbstractObject extends AbstractData {
    # RByte RByte()
    # RShort RShort()
    # RInteger RInteger()
    # RLong RLong()
    # RFloat RFloat()
    # RDouble RDouble()
    # RBoolean RBoolean()
    # RByteArray RByteArray()
    # RCharacter RCharacter()
    # RRItemStack() RItemStack()
    # RJson RJson()
    # RString RString()
    # RUUID RUUID()
    # RWrapper RWrapper()
    # REnum REnum()
}

AbstractObject *-- AbstractData

abstract SimpleAbstractObject extends AbstractObject implements SimpleInterface {

}

class REnum extends SimpleAbstractObject {

}

REnum *-- RString


class DataGenerator<T extends AbstractData> {
    + {static} AbstractData<?> createAnonymous()
    + {static} void delete()
    + T create()
}

DataGenerator - AbstractData



AbstractData *-- Bytes
CompositeData *-- Bytes
CollectionData *-- Bytes
AbstractObject *-- Bytes
RWrapper *-- Bytes
SimpleData *-- Bytes

Bytes -- ByteDataInterface
Bytes -- JedisCommunicationChannel



@enduml