name: Firecord
version: '${project.version}'
main: net.legendofwar.firecord.spigot.FirecordSpigot
api-version: 1.19
authors: [ FreeSoccerHDX, tobi20, Moritzwied ]
commands:
  firecord:
    description: Firecord utils
    aliases: [fc, fcord]